# staticmethod

In [5]:
# an example of staticmethod usage in python: same script with and without staticmethod
# staticmethod is a decorator that makes a method static, i.e. it can be called on the class itself, without creating an instance of the class
# this is useful when you want to create a method that is related to the class, but doesn't need to access any instance variables

# without staticmethod
class MyClass:
    def __init__(self, value):
        self.value = value

    def get_value(self):
        return self.value

    def set_value(self, value):
        self.value = value

    def add_values(self, value1, value2):
        return value1 + value2
    
    
# with staticmethod
class MyClassStatic:
    def __init__(self, value):
        self.value = value

    def get_value(self):
        return self.value

    def set_value(self, value):
        self.value = value

    @staticmethod
    def add_values(value1, value2):
        return value1 + value2
    
    
print('without staticmethod:')
my_class = MyClass(10)
print(my_class.get_value())
my_class.set_value(20)
print(my_class.get_value())
print(my_class.add_values(10, 20))


print('with staticmethod:')
my_class_static = MyClassStatic(10)
print(my_class_static.get_value())
my_class_static.set_value(20)
print(my_class_static.get_value())
print(MyClassStatic.add_values(10, 20))

without staticmethod:
10
20
30
with staticmethod:
10
20
30


In [6]:
class MathOperations:
    def add(a, b):
        return a + b

# Create an instance of MathOperations
math_ops = MathOperations()

# Call the method using the instance
# print(math_ops.add(5, 3))  # This will raise a TypeError because 'self' is missing

class MathOperations_static:
    @staticmethod
    def add(a, b):
        return a + b

# Call the method using the class name
print(MathOperations_static.add(5, 3))  # Output: 8

# You can also call it using an instance, but it's not required
math_ops = MathOperations_static()
print(math_ops.add(5, 3))  # Output: 8

8
8


# .squeeze

In [7]:
import torch

# Create a tensor of shape [3, 1]
x = torch.tensor([[1], [2], [3]])
print("Original tensor:")
print(x)
print("Shape of the original tensor:", x.shape)

# Apply squeeze(-1)
x_squeezed = x.squeeze(-1)
print("\nTensor after squeeze(-1):")
print(x_squeezed)
print("Shape of the squeezed tensor:", x_squeezed.shape)


Original tensor:
tensor([[1],
        [2],
        [3]])
Shape of the original tensor: torch.Size([3, 1])

Tensor after squeeze(-1):
tensor([1, 2, 3])
Shape of the squeezed tensor: torch.Size([3])


# Lab4 Scratch

In [12]:
# Create a tensor of shape [3, 1]
x = torch.tensor([1, 2, 3])
print(x.squeeze(0))

tensor([1, 2, 3])


In [15]:
import torch
from torch import Tensor

def _init_glorot(in_features: int, out_features: int) -> Tensor:
    """Init a weight matrix with glorot initialization."""
    b = torch.sqrt(torch.tensor([6. / (in_features + out_features)]))
    return (2 * b) * torch.rand(in_features, out_features) - b


In [17]:
weights = _init_glorot(5, 3)

In [18]:
bias = torch.zeros(3)

In [22]:
x = torch.randn(5)

In [23]:
x

tensor([ 1.6383, -1.6605, -1.7663,  0.3726, -1.0319])

In [24]:
print(x @ weights + bias)

tensor([0.9201, 1.8753, 0.1421])


In [26]:
class MSELoss:
    @staticmethod
    def forward(y_true: Tensor, y_pred: Tensor) -> Tensor:
        return torch.mean((y_true - y_pred)**2)

    @staticmethod
    def get_gradient(y_true: Tensor, y_pred: Tensor) -> Tensor:
        return 2 * (y_pred - y_true) / len(y_true)

In [27]:
loss = MSELoss()
loss.forward(torch.rand(3),x @ weights + bias)

tensor(0.5671)