In [1]:
import numpy as np
from scipy.special import softmax

# Define embeddings for each word in the sentence "Your cat is a lovely cat"
embeddings = {
    "Your": np.array([1, 0, 1]),
    "cat": np.array([0, 1, 1]),
    "is": np.array([1, 1, 0]),
    "a": np.array([0, 1, 0]),
    "lovely": np.array([1, 0, 0]),
}

# Create input matrix with embeddings for the sentence
input_matrix = np.array([
    embeddings["Your"],
    embeddings["cat"],
    embeddings["is"],
    embeddings["a"],
    embeddings["lovely"],
    embeddings["cat"],  # Repeating "cat" at the end
])

# Step 1: Calculate Attention Scores (Q * K^T)
# Since Q = K = input_matrix, we can do a simple dot product of input_matrix with its transpose
attention_scores = np.dot(input_matrix, input_matrix.T)
print("Attention Scores:\n", attention_scores)

# Step 2: Apply Softmax to get Attention Weights
attention_weights = softmax(attention_scores, axis=1)
print("\nAttention Weights (after softmax):\n", attention_weights)

# Step 3: Multiply Attention Weights by the Value (V) Matrix (which is the same as input_matrix here)
output = np.dot(attention_weights, input_matrix)
print("\nOutput Matrix:\n", output)


Attention Scores:
 [[2 1 1 0 1 1]
 [1 2 1 1 0 2]
 [1 1 2 1 1 1]
 [0 1 1 1 0 1]
 [1 0 1 0 1 0]
 [1 2 1 1 0 2]]

Attention Weights (after softmax):
 [[0.38360429 0.14112013 0.14112013 0.05191519 0.14112013 0.14112013]
 [0.11357902 0.30873978 0.11357902 0.11357902 0.04178339 0.30873978]
 [0.12956251 0.12956251 0.35218743 0.12956251 0.12956251 0.12956251]
 [0.0776812  0.2111594  0.2111594  0.2111594  0.0776812  0.2111594 ]
 [0.24368619 0.08964714 0.24368619 0.08964714 0.24368619 0.08964714]
 [0.11357902 0.30873978 0.11357902 0.11357902 0.04178339 0.30873978]]

Output Matrix:
 [[0.66584455 0.47527558 0.66584455]
 [0.26894142 0.8446376  0.73105858]
 [0.61131246 0.74087497 0.38868754]
 [0.3665218  0.8446376  0.5       ]
 [0.73105858 0.51262761 0.42298047]
 [0.26894142 0.8446376  0.73105858]]


In [2]:
input_matrix

array([[1, 0, 1],
       [0, 1, 1],
       [1, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 1]])

In [3]:
output

array([[0.66584455, 0.47527558, 0.66584455],
       [0.26894142, 0.8446376 , 0.73105858],
       [0.61131246, 0.74087497, 0.38868754],
       [0.3665218 , 0.8446376 , 0.5       ],
       [0.73105858, 0.51262761, 0.42298047],
       [0.26894142, 0.8446376 , 0.73105858]])