In [1]:
import pandas as pd
import numpy as np
import datetime

# Ridge regression

In [2]:
import numpy as np

# Define the parameter vector with 3 parameters (coefficients)
theta = np.array([[2], [-1], [0.5]])

# Create a feature matrix representing a dataset with 10 observations and 3 features
# Using random numbers for simplicity
np.random.seed(0)  # Seed for reproducibility
X = np.random.rand(10, 3)

# Define the lambda parameter for ridge regression
lambda_param = 0.1

# Compute the identity matrix of size equal to the number of features
identity_matrix = np.identity(3)

# Compute X^T * X (transpose of X multiplied by X)
XTX = np.dot(X.T, X)

# Add lambda times the identity matrix to the diagonal of X^T * X
# This is the ridge penalty term that helps prevent overfitting
ridge_XTX = XTX + lambda_param * identity_matrix

# Create a target variable 'y' with 10 random values
y = np.random.rand(10, 1)

# Calculate the pseudo-inverse of the modified matrix for ridge regression
# This involves inverting the ridge_XTX matrix and then multiplying by X^T
ridge_pseudo_inverse = np.linalg.inv(ridge_XTX).dot(X.T)

# Calculate the ridge regression coefficients
theta_ridge = ridge_pseudo_inverse.dot(y)

# The modified matrix and the ridge coefficients are now available
# Displaying the results
print("Modified matrix for Ridge Regression (X^T X + lambda * I):")
print(ridge_XTX)
print("\nRidge Regression Coefficients (theta_ridge):")
print(theta_ridge)


Modified matrix for Ridge Regression (X^T X + lambda * I):
[[3.51744059 3.45915961 3.21408384]
 [3.45915961 4.72191368 3.58515223]
 [3.21408384 3.58515223 4.54659492]]

Ridge Regression Coefficients (theta_ridge):
[[0.15390983]
 [0.18289919]
 [0.49784543]]


In [3]:
theta

array([[ 2. ],
       [-1. ],
       [ 0.5]])

In [4]:
X

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194]])

In [6]:
X*theta.T

array([[ 1.09762701, -0.71518937,  0.30138169],
       [ 1.08976637, -0.4236548 ,  0.32294706],
       [ 0.87517442, -0.891773  ,  0.48183138],
       [ 0.76688304, -0.79172504,  0.26444746],
       [ 1.13608912, -0.92559664,  0.03551803],
       [ 0.1742586 , -0.0202184 ,  0.41630992],
       [ 1.5563135 , -0.87001215,  0.48930917],
       [ 1.59831713, -0.46147936,  0.39026459],
       [ 0.23654885, -0.63992102,  0.07167664],
       [ 1.88933783, -0.52184832,  0.20733097]])

In [8]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.dot(X.T, X)

array([[3.41744059, 3.45915961, 3.21408384],
       [3.45915961, 4.62191368, 3.58515223],
       [3.21408384, 3.58515223, 4.44659492]])

In [9]:
lambda_param

0.1

In [10]:
ridge_XTX = XTX + lambda_param * identity_matrix

In [11]:
ridge_XTX

array([[3.51744059, 3.45915961, 3.21408384],
       [3.45915961, 4.72191368, 3.58515223],
       [3.21408384, 3.58515223, 4.54659492]])

In [14]:
np.linalg.inv(ridge_XTX)

array([[ 1.25936927, -0.61459344, -0.40564585],
       [-0.61459344,  0.82766616, -0.21817522],
       [-0.40564585, -0.21817522,  0.67874337]])

In [15]:
ridge_XTX

array([[3.51744059, 3.45915961, 3.21408384],
       [3.45915961, 4.72191368, 3.58515223],
       [3.21408384, 3.58515223, 4.54659492]])