In [1]:
import numpy as np

# Define the random variables X and Y
np.random.seed(0)
X = np.random.normal(0, 1, 1000)  # X is normally distributed with mean 0 and std 1
Y = 2 * X + np.random.normal(0, 1, 1000)  # Y is a linear function of X plus some noise

# Calculate the expected value of Y
expected_Y = np.mean(Y)

# Calculate the expected value of Y conditional on X
conditional_expectations = [np.mean(Y[X == x]) for x in np.unique(X)]
expected_conditional_Y = np.mean(conditional_expectations)

expected_Y, expected_conditional_Y

(-0.07689647466422721, -0.0768964746642273)

In [15]:
# Calculate the expected value of X
expected_X = np.mean(X)

# Calculate the expected value of X conditional on Y
# To ensure we have a manageable number of unique Y values, let's round Y to one decimal place
Y_rounded = np.round(Y, 1)
conditional_expectations_X = [np.mean(X[Y_rounded == y]) for y in np.unique(Y_rounded)]
expected_conditional_X = np.mean(conditional_expectations_X)

expected_X, expected_conditional_X

(-0.045256707490195384, -0.07985260415302939)

In [16]:
# Calculate the expected value of X
expected_X = np.mean(X)

# Calculate the expected value of X conditional on Y
# To ensure we have a manageable number of unique Y values, let's round Y to one decimal place
#Y_rounded = np.round(Y, 1)
conditional_expectations_X = [np.mean(X[Y == y]) for y in np.unique(Y)]
expected_conditional_X = np.mean(conditional_expectations_X)

expected_X, expected_conditional_X

(-0.045256707490195384, -0.04525670749019531)

In [6]:
[x for x in np.unique(X)][:5]

[-3.0461430547999266,
 -2.8345545052747023,
 -2.77259275642665,
 -2.7396771671895563,
 -2.659172237996741]

In [13]:
X[:5]

array([1.76405235, 0.40015721, 0.97873798, 2.2408932 , 1.86755799])

In [14]:
Y[X == 1.76405235]

array([], dtype=float64)

In [12]:
Y[X == 2]

array([], dtype=float64)

In [19]:
len(X)
len(np.unique(X))

1000

In [20]:
len(Y)
len(np.unique(Y))

1000

In [21]:
# Redefining X and Y with fewer unique values and a smaller dataset for simplicity
np.random.seed(0)
X = np.random.choice([0, 1, 2, 3, 4], 100)  # X is now chosen from 5 unique values
Y = X + np.random.choice([-1, 0, 1], 100)  # Y is X plus a small noise from three unique values

# Calculate the expected value of X
expected_X = np.mean(X)

# Calculate the expected value of X conditional on Y
conditional_expectations_X = [np.mean(X[Y == y]) for y in np.unique(Y)]
expected_conditional_X = np.mean(conditional_expectations_X)

expected_X, expected_conditional_X



(1.96, 1.996382189239332)

In [22]:
X

array([4, 0, 3, 3, 3, 1, 3, 2, 4, 0, 0, 4, 2, 1, 0, 1, 1, 0, 1, 4, 3, 0,
       3, 0, 2, 3, 0, 1, 3, 3, 3, 0, 1, 1, 1, 0, 2, 4, 3, 3, 2, 4, 2, 0,
       0, 4, 0, 4, 1, 4, 1, 2, 2, 0, 1, 1, 1, 1, 3, 3, 2, 3, 0, 3, 4, 1,
       2, 4, 3, 4, 4, 4, 3, 4, 4, 4, 0, 4, 3, 2, 0, 1, 1, 3, 0, 0, 1, 2,
       4, 2, 0, 3, 2, 2, 0, 1, 0, 2, 2, 3])

In [26]:
X[Y == 3]

array([3, 2, 4, 2, 3, 2, 4, 2, 4, 4, 3, 3, 4, 3, 4, 4, 3, 2, 2, 2, 3])

In [24]:
len([np.mean(X[Y == y]) for y in np.unique(Y)])

7

In [25]:
[np.mean(X[Y == y]) for y in np.unique(Y)]

[0.0, 0.6428571428571429, 0.6818181818181818, 2.15, 3.0, 3.5, 4.0]

In [27]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Generate a simple dataset with 50 data points, with a single feature and a binary class
np.random.seed(0)
X = np.random.rand(50, 1) # 50 data points with 1 feature
y = (X[:, 0] > 0.5).astype(int)  # Class 0 if feature <= 0.5, else class 1

# Split the dataset into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

# Train a simple Gaussian Naive Bayes model
model = GaussianNB()
model.fit(X_train, y_train)

# Predict probabilities for the test set
probabilities = model.predict_proba(X_test)

# Let's see the first 5 probabilities to understand P(y = l | x = x)
probabilities[:5]


array([[1.78432899e-01, 8.21567101e-01],
       [1.54123364e-01, 8.45876636e-01],
       [2.30094188e-04, 9.99769906e-01],
       [6.39511140e-01, 3.60488860e-01],
       [2.78131175e-02, 9.72186883e-01]])

In [28]:
X

array([[0.5488135 ],
       [0.71518937],
       [0.60276338],
       [0.54488318],
       [0.4236548 ],
       [0.64589411],
       [0.43758721],
       [0.891773  ],
       [0.96366276],
       [0.38344152],
       [0.79172504],
       [0.52889492],
       [0.56804456],
       [0.92559664],
       [0.07103606],
       [0.0871293 ],
       [0.0202184 ],
       [0.83261985],
       [0.77815675],
       [0.87001215],
       [0.97861834],
       [0.79915856],
       [0.46147936],
       [0.78052918],
       [0.11827443],
       [0.63992102],
       [0.14335329],
       [0.94466892],
       [0.52184832],
       [0.41466194],
       [0.26455561],
       [0.77423369],
       [0.45615033],
       [0.56843395],
       [0.0187898 ],
       [0.6176355 ],
       [0.61209572],
       [0.616934  ],
       [0.94374808],
       [0.6818203 ],
       [0.3595079 ],
       [0.43703195],
       [0.6976312 ],
       [0.06022547],
       [0.66676672],
       [0.67063787],
       [0.21038256],
       [0.128

In [29]:
y

array([1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0])